name: Build Native Addon

# 当有代码推送到主分支时，自动触发此流程
on:
  push:
    branches: [ main, master ] # 根据您的主分支名字修改
  workflow_dispatch: # 允许手动触发

jobs:
  build-addon:
    # 关键：指定运行在一个最新的 macOS 虚拟机上
    # 这个虚拟机会自带一个非常新的 Xcode 版本
    runs-on: macos-latest

    steps:
      # 第一步：把您的代码拉取到虚拟机中
      - name: Checkout code
        uses: actions/checkout@v4

      # 第二步：安装 pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8 # 或者您使用的 pnpm 版本

      # 第三步：安装 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 建议使用一个 LTS 版本的 Node.js
          cache: 'pnpm'

      # 第四步：安装项目所有依赖
      - name: Install dependencies
        run: pnpm install

      # 第五步：生成 Xcode 项目文件
      - name: Configure addon build
        run: pnpm run addon:configure

      # 第六步：编译原生插件
      - name: Build addon
        run: pnpm run addon:build

      # 第七步（重要）：上传编译好的插件文件
      # 流程结束后，您可以从 Actions 页面下载这个文件
      - name: Upload addon artifact
        uses: actions/upload-artifact@v4
        with:
          name: speech-recognizer-addon
          path: native-addons/speech-recognizer/build/Release/speech_recognizer.node